services:

  frontend:
    build:
      context: ./frontend
    container_name: portfolio_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    depends_on:
      - minishell-backend

  minishell-backend:
    build:
      context: ./minishell-backend
    container_name: portfolio_backend
    ports:
      - "4000:4000"
    volumes:
      - ./minishell-backend:/app
      - ${DOCKER_SOCKET:-/var/run/docker.sock}:/var/run/docker.sock
    environment:
      NODE_ENV: development
      MINISHELL_IMAGE: isly-minishell:latest
    mem_limit: 512m
    pids_limit: 128